---
- hosts: centos
  become: true
  tasks:
    - name: update repository index
      dnf:
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install Apache package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"

    - name: install PHP package
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "RedHat"

